export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';
export const DISCONNECT = 'DISCONNECT';

export const MESSAGE_SENDING = 'MESSAGE_SENDING';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';

export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';

export const SHOW_NICKNAME_FORM = 'SHOW_NICKNAME_FORM';
export const HIDE_NICKNAME_FORM = 'HIDE_NICKNAME_FORM';
export const CHANGE_NICKNAME_REQUEST = 'CHANGE_NICKNAME_REQUEST';
export const CHANGE_NICKNAME_SUCCESS = 'CHANGE_NICKNAME_SUCCESS';
export const USER_CHANGED_NICKNAME = 'USER_CHANGED_NICKNAME';

export const TOGGLE_USERS_LIST = 'TOGGLE_USERS_LIST';
